[tool.poetry]
name = "aula08"
version = "0.1.0"
description = ""
authors = ["Marcelo Augusto Kniss <mkniss@alincoit.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
